name: 'SFTP uploader'
author: 'wycode.cn'
branding:
  color: 'green'
  icon: 'upload'
description: 'upload files to server via SFTP'
inputs:
  host:
    required: true
  port:
    required: false
    default: 22
  username:
    required: false
    default: 'root'
  password:
    required: true
  localDir:
    required: true
  remoteDir:
    required: true
  dryRun:
    required: false
    default: false
  privateKey:
    required: false
    default: ''
  passphrase:
    required: false
    default: ''
  agent:
    required: false
    default: ''
  excludeMode:
    required: false
    default: 'remove'
  exclude:
    required: false
    default: ''
  forceUpload:
    required: false
    default: false
  keepExtraFiles:
    required: false
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
